// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CpaInferenceErrorNotification = { body: string | null, headers: { [key in string]?: Array<string> } | null, requestId: string, httpStatus: number, message: string, };
