// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Actual inference transport exchanges, including attempts made during auth recovery.
 */
export type CpaInferenceUpstreamNotification = { "kind": "request", requestId: string, url: string, method: string, headers: { [key in string]?: Array<string> }, body: string, accessTokenSha256: string | null, oaiLbNode: string | null, } | { "kind": "response", requestId: string, statusCode: number, headers: { [key in string]?: Array<string> }, body: string | null, oaiLbNode: string | null, } | { "kind": "body", requestId: string, bodyBase64: string, } | { "kind": "error", requestId: string, message: string, };
